# The valley towns added for summer: places to ride with no ski area in the app.
# Hand data lives here; build.py adds drive times (fromOrigin) from route-planner results.
TOWNS = [
  {"id": "it-finale-ligure", "country": "IT", "name": "Finale Ligure", "region": "Liguria", "coords": [8.3436, 44.1696],
   "altitude": 10, "townSize": "medium", "price": 2, "stayPerPerson": 75, "family": True, "vibes": ["lively", "town"],
   "character": "Seaside town and the home of Italian enduro. Rocky trails run from the hills down to the beach, and shuttle vans take you up.",
   "transfer": "Shared transfer or car. About 2h30 from Turin or Milan. Train to Finale Ligure Marina.", "rail": "Trenitalia trains",
   "searchName": "Finale Ligure",
   "bike": {"level": "awesome", "suits": ["intermediate", "expert"], "styles": ["enduro", "downhill", "xc", "ebike"], "pass": 30,
            "season": {"open": "2027-03-01", "close": "2027-11-30"},
            "note": "Enduro heartland. Shuttle vans take you up to long rocky trails that finish by the sea. Best in spring and autumn. Hot in July and August, so ride early."}},
  {"id": "it-riva-del-garda", "country": "IT", "name": "Riva del Garda", "region": "Trentino", "coords": [10.8410, 45.8858],
   "altitude": 70, "townSize": "medium", "price": 2, "stayPerPerson": 85, "family": True, "vibes": ["lively", "town"],
   "character": "Lake town under steep cliffs and a big name in mountain biking. Trails start from the edge of town, with shuttles and lifts for the long ones.",
   "transfer": "Shared transfer or car. About 1h45 from Bergamo, 2h30 from Milan. Bus to Trento for trains.", "rail": "",
   "searchName": "Riva del Garda",
   "bike": {"level": "awesome", "suits": ["beginner", "intermediate", "expert"], "styles": ["enduro", "xc", "ebike", "downhill", "kids"], "pass": 28,
            "season": {"open": "2027-03-15", "close": "2027-11-15"},
            "note": "A mountain biking capital. Rocky lake-side trails, long climbs and shuttle rides, plus easy lake paths for families. Hot in summer, so ride early."}},
  {"id": "ch-locarno", "country": "CH", "name": "Locarno and Ascona", "region": "Ticino", "coords": [8.7957, 46.1708],
   "altitude": 200, "townSize": "medium", "price": 3, "stayPerPerson": 125, "family": True, "vibes": ["upmarket", "town"],
   "character": "Sunny Italian-Swiss lakeside towns on Lake Maggiore. Forest trails above the lake, a cable car to Cardada, and a mild climate.",
   "transfer": "Shared transfer or car. About 2h30 from Zurich, 1h from Milan Malpensa. Direct trains from Zurich through the Gotthard tunnel.", "rail": "SBB trains",
   "searchName": "Locarno",
   "bike": {"level": "good", "suits": ["beginner", "intermediate", "expert"], "styles": ["xc", "enduro", "ebike"], "pass": 25,
            "season": {"open": "2027-04-01", "close": "2027-11-15"},
            "note": "Warm, sunny riding around the lake, with trails from the Cardada cable car and long forest routes. Not a lift-served bike park."}},
  {"id": "at-leogang", "country": "AT", "name": "Leogang", "region": "Salzburg", "coords": [12.7318, 47.4339],
   "altitude": 780, "townSize": "small", "price": 2, "stayPerPerson": 85, "family": True, "vibes": ["traditional", "quiet"],
   "character": "Quiet farming village and the home of Bikepark Leogang, a World Cup venue with lifts almost at the door.",
   "transfer": "Shared transfer or car. About 1h45 from Salzburg, 1h30 from Munich.", "rail": "ÖBB trains",
   "searchName": "Leogang",
   "bike": {"level": "awesome", "suits": ["beginner", "intermediate", "expert"], "styles": ["flow", "downhill", "enduro", "kids", "ebike"], "pass": 49,
            "season": {"open": "2027-05-22", "close": "2027-10-04"},
            "note": "Bikepark Leogang: a World Cup downhill venue with the widest range in Austria, from kids' tracks to steep expert lines. Joint pass with Saalbach."}},
]
